[package]
name = "temps"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.20", features = ["cargo"] }
colored = "3.0.0"
indexmap = "2.9.0"
serde_json = "1.0"
